spring.application.name=DBTest
spring.datasource.url=jdbc:postgresql://localhost:5432/UserTest
spring.datasource.username=postgres
spring.datasource.password=9678
spring.jpa.hibernate.ddl-auto=update
